server:
  port: 8080

spring:
  application:
    name: api-gateway

  profiles:
    active: local # default value

  config:
    # Note: use "SPRING_CLOUD_CONFIG_URI=..." on prod to override this
    import: "optional:configserver:http://localhost:8888/"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:5173"
              - "http://127.0.0.1:5173"
            allowedMethods: ["GET","POST","PUT","PATCH","DELETE","OPTIONS"]
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

        - id: user-service-users
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter

        - id: user-service-friends
          uri: lb://user-service
          predicates:
            - Path=/friends/**
          filters:
            - AuthenticationFilter

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chats/**
          filters:
            - AuthenticationFilter

        # WebSockets route (SockJS XHR fallback + native WS upgrade)
        - id: chat-service-ws
          uri: lb://chat-service
          predicates:
            - Path=/ws/**

        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/media/**
          filters:
            - AuthenticationFilter

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,threshold"
  tracing:
    sampling:
      probability: 1.0