server:
  port: 9001

spring:
  application:
    name: user-service

  profiles:
    active: local # default value

  config:
    # Note: use "SPRING_CLOUD_CONFIG_URI=..." on prod to override this
    import: "optional:configserver:http://localhost:8888/"

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/changelog-root.xml
    default-schema: public

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE